// The Faktor Native Protocol v1 client (docs/native-protocol.md): a typed
// java.net.http client of the daemon's OWN surface. This client is what the
// real frontend renders from; there is no compatibility wire surface.
//
// Rules observed:
//  - auth is the ephemeral password generated by BackendProcessManager and
//    handed to the child through the environment (protected channel, never
//    argv or disk): `Authorization: Bearer <password>`.
//  - every response body is read through a streaming byte cap; oversized
//    bodies are closed and rejected, never buffered unbounded.
//  - every request carries a timeout; non-2xx bodies are mapped to
//    NativeApiException with the daemon's `{error:{code,message,retryable}}`.
//  - shapes are parsed by dev.faktor.shared native parsers, so drift is a
//    loud NativeProtocolException, never a silently wrong UI.
package dev.faktor.backend

import dev.faktor.shared.JsonCodec
import dev.faktor.shared.JsonValue
import dev.faktor.shared.NativeAbortAck
import dev.faktor.shared.NativeAgent
import dev.faktor.shared.NativeAgentControlAck
import dev.faktor.shared.NativeApiException
import dev.faktor.shared.NativeBillingUsage
import dev.faktor.shared.NativeBoardPage
import dev.faktor.shared.NativeBoardPost
import dev.faktor.shared.NativeCompletionContract
import dev.faktor.shared.NativeCreditGrant
import dev.faktor.shared.NativeEntitlementSnapshot
import dev.faktor.shared.NativeEventPage
import dev.faktor.shared.NativeEvidence
import dev.faktor.shared.NativeEvidenceRetrieval
import dev.faktor.shared.NativeHealth
import dev.faktor.shared.NativeIdentity
import dev.faktor.shared.NativeMessagePage
import dev.faktor.shared.NativeModelInfo
import dev.faktor.shared.NativeProjection
import dev.faktor.shared.NativePromptReceipt
import dev.faktor.shared.NativeOrchestratorGraph
import dev.faktor.shared.NativePermissionAck
import dev.faktor.shared.NativePermissionEntry
import dev.faktor.shared.NativePresentationAck
import dev.faktor.shared.NativeProtocolException
import dev.faktor.shared.NativeProviderInfo
import dev.faktor.shared.NativeReady
import dev.faktor.shared.NativeRequests
import dev.faktor.shared.NativeSessionCreated
import dev.faktor.shared.NativeSessionSummary
import dev.faktor.shared.NativeSessionUsage
import dev.faktor.shared.NativeTaskRun
import dev.faktor.shared.NativeTaskCompletionSteps
import dev.faktor.shared.NativeTaskProof
import dev.faktor.shared.NativeTaskRunCancelled
import dev.faktor.shared.NativeTaskRunStarted
import dev.faktor.shared.NativeTaskVerification
import dev.faktor.shared.NativeTaskView
import dev.faktor.shared.NativeTerminalEventPage
import dev.faktor.shared.NativeTerminalOutput
import dev.faktor.shared.NativeTerminalPage
import dev.faktor.shared.NativeTerminalSpawned
import dev.faktor.shared.NativeTournament
import dev.faktor.shared.NativeTournamentDecision
import dev.faktor.shared.NativeTournamentStarted
import dev.faktor.shared.NativeTournamentSummary
import dev.faktor.shared.NativeUsageTotals
import dev.faktor.shared.NativeVerificationView
import dev.faktor.shared.parseNativeAbortAck
import dev.faktor.shared.parseNativeAgentControlAck
import dev.faktor.shared.parseNativeAgents
import dev.faktor.shared.parseNativeBillingUsage
import dev.faktor.shared.parseNativeBoardPage
import dev.faktor.shared.parseNativeBoardPost
import dev.faktor.shared.parseNativeCreditGrant
import dev.faktor.shared.parseNativeEntitlements
import dev.faktor.shared.parseNativeEventPage
import dev.faktor.shared.parseNativeEvidence
import dev.faktor.shared.parseNativeEvidenceRetrieval
import dev.faktor.shared.parseNativeHealth
import dev.faktor.shared.parseNativeIdentity
import dev.faktor.shared.parseNativeMessagePage
import dev.faktor.shared.parseNativeModelCatalog
import dev.faktor.shared.parseNativeOrchestratorGraph
import dev.faktor.shared.parseNativePermissionAck
import dev.faktor.shared.parseNativePermissionList
import dev.faktor.shared.parseNativePresentationAck
import dev.faktor.shared.parseNativeProjection
import dev.faktor.shared.parseNativePromptReceipt
import dev.faktor.shared.parseNativeProviders
import dev.faktor.shared.parseNativeReady
import dev.faktor.shared.parseNativeSessionCreated
import dev.faktor.shared.parseNativeSessionList
import dev.faktor.shared.parseNativeSessionUsage
import dev.faktor.shared.parseNativeTaskRunCancelled
import dev.faktor.shared.parseNativeTaskRunStarted
import dev.faktor.shared.parseNativeTaskRuns
import dev.faktor.shared.parseNativeTaskCompletionSteps
import dev.faktor.shared.parseNativeTaskProof
import dev.faktor.shared.parseNativeTaskVerification
import dev.faktor.shared.parseNativeTaskViews
import dev.faktor.shared.parseNativeTerminalEventPage
import dev.faktor.shared.parseNativeTerminalOutput
import dev.faktor.shared.parseNativeTerminalPage
import dev.faktor.shared.parseNativeTerminalSpawned
import dev.faktor.shared.parseNativeTournament
import dev.faktor.shared.parseNativeTournamentDecision
import dev.faktor.shared.parseNativeTournamentStarted
import dev.faktor.shared.parseNativeTournamentSummaries
import dev.faktor.shared.parseNativeUsage
import dev.faktor.shared.parseNativeVerificationView
import java.io.ByteArrayOutputStream
import java.io.IOException
import java.io.InputStream
import java.math.BigInteger
import java.net.URI
import java.net.URLEncoder
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.time.Duration

private const val REQUEST_ERROR_SNIPPET = 400

/**
 * Typed client of the daemon's native surface. One instance per daemon
 * connection; [bearerToken] is the connection password and never logged.
 */
class NativeClient(
    val baseUrl: String,
    val bearerToken: String,
    private val timeoutMs: Long = DEFAULT_TIMEOUT_MS,
    private val maxBodyBytes: Long = DEFAULT_MAX_BODY_BYTES,
    /**
     * The control-plane credential (`x-faktor-control-token`): an auth-session
     * or service-account token, NEVER the daemon password. Absent = no
     * control-plane principal; the billing/identity routes then refuse loudly
     * and the usage panel renders that refusal (never fabricated numbers).
     */
    private val controlToken: String? = null
) {
    companion object {
        const val DEFAULT_TIMEOUT_MS = 15_000L
        const val DEFAULT_MAX_BODY_BYTES = 4L * 1024 * 1024
        const val EVIDENCE_MAX_BODY_BYTES = 32L * 1024 * 1024
        const val READY_POLL_MS = 100L

        fun forConnection(
            connection: BackendConnection,
            controlToken: String? = null,
            // Submitting a prompt starts real work (candidate prep,
            // verification, integration); the 15 s default read timeout can
            // expire on a loaded machine even though the run is healthy.
            // Long-operation callers pass a generous budget.
            timeoutMs: Long = DEFAULT_TIMEOUT_MS
        ): NativeClient =
            NativeClient(
                connection.baseUrl,
                connection.password,
                timeoutMs = timeoutMs,
                controlToken = controlToken
            )
    }

    private val http: HttpClient = HttpClient.newBuilder()
        .connectTimeout(Duration.ofMillis(timeoutMs))
        .build()

    // ------------------------------------------------------------ liveness

    fun health(): NativeHealth = parseNativeHealth(request("GET", "/native/health"))

    fun ready(): NativeReady = parseNativeReady(request("GET", "/native/ready"))

    /** Polls readiness until true or the deadline; returns the last ready state. */
    fun awaitReady(timeoutMs: Long = 10_000L): NativeReady {
        val deadline = System.currentTimeMillis() + timeoutMs
        var last = NativeReady(false)
        while (System.currentTimeMillis() < deadline) {
            last = try {
                ready()
            } catch (e: NativeApiException) {
                if (e.status != 503) throw e
                NativeReady(false)
            }
            if (last.ready) return last
            Thread.sleep(READY_POLL_MS)
        }
        return last
    }

    // ------------------------------------------------------------- sessions

    fun createSession(
        provider: String,
        model: String,
        workspace: String? = null,
        title: String? = null
    ): NativeSessionCreated = parseNativeSessionCreated(
        request(
            "POST", "/native/session", null,
            NativeRequests.createSession(provider, model, workspace, title)
        )
    )

    fun listSessions(): List<NativeSessionSummary> =
        parseNativeSessionList(request("GET", "/native/sessions"))

    fun modelCatalog(): List<NativeModelInfo> =
        parseNativeModelCatalog(request("GET", "/models"))

    fun prompt(sessionId: String, prompt: String, files: List<String>? = null): NativePromptReceipt =
        parseNativePromptReceipt(
            request(
                "POST", "/native/session/" + encode(sessionId) + "/prompt", null,
                NativeRequests.prompt(sessionId, prompt, files)
            )
        )

    fun abortSession(sessionId: String, opId: String? = null): NativeAbortAck =
        parseNativeAbortAck(
            request(
                "POST", "/native/session/" + encode(sessionId) + "/abort", null,
                NativeRequests.abort(sessionId, opId)
            )
        )

    fun projection(sessionId: String): NativeProjection =
        parseNativeProjection(
            request("GET", "/session/" + encode(sessionId) + "/projection")
        )

    fun messages(sessionId: String, before: Long? = null, limit: Long? = null): NativeMessagePage =
        parseNativeMessagePage(
            request(
                "GET", "/native/messages",
                query("session" to sessionId, "before" to before?.toString(), "limit" to limit?.toString())
            )
        )

    fun events(sessionId: String, after: Long? = null, limit: Long? = null): NativeEventPage =
        parseNativeEventPage(
            request(
                "GET", "/native/events",
                query("session" to sessionId, "after" to after?.toString(), "limit" to limit?.toString())
            )
        )

    // ------------------------------------------------------------ task runs

    fun taskRuns(sessionId: String): List<NativeTaskRun> = parseNativeTaskRuns(
        request("GET", "/native/session/" + encode(sessionId) + "/task-runs")
    )

    fun taskRunState(sessionId: String, runId: String): NativeTaskRun {
        val runs = taskRuns(sessionId)
        for (run in runs) {
            if (run.runId == runId) return run
        }
        throw NativeApiException(404, "not_found", "task run $runId under session $sessionId", false)
    }

    fun startTaskRun(
        sessionId: String,
        goal: String,
        criteria: List<String>? = null,
        model: String? = null,
        maxTokens: Long? = null,
        maxCostMicro: BigInteger? = null,
        mutationMode: String? = null,
        files: List<String>? = null,
        completionContract: NativeCompletionContract? = null
    ): NativeTaskRunStarted = parseNativeTaskRunStarted(
        request(
            "POST", "/native/session/" + encode(sessionId) + "/task-runs", null,
            NativeRequests.startTaskRun(
                goal, criteria, model, maxTokens, maxCostMicro, mutationMode, files,
                completionContract
            )
        )
    )

    fun cancelTaskRun(sessionId: String, runId: String): NativeTaskRunCancelled =
        parseNativeTaskRunCancelled(
            request(
                "POST",
                "/native/session/" + encode(sessionId) + "/task-runs/" + encode(runId) + "/cancel"
            )
        )

    fun taskViews(sessionId: String): List<NativeTaskView> = parseNativeTaskViews(
        request("GET", "/native/session/" + encode(sessionId) + "/tasks")
    )

    // ------------------------------------------------------ coordination board

    /**
     * One bounded newest-first page of the path session's run-family board.
     * `since` is the exclusive cursor for the next OLDER page (the value a
     * previous page returned as `next_before_revision`).
     */
    fun board(sessionId: String, since: Long? = null, limit: Long? = null): NativeBoardPage =
        parseNativeBoardPage(
            request(
                "GET", "/native/session/" + encode(sessionId) + "/board",
                query("since" to since?.toString(), "limit" to limit?.toString())
            )
        )

    /** Append one bounded post AS the session (201); the server is the guard. */
    fun boardPost(
        sessionId: String,
        subject: String,
        body: String,
        refs: List<String>? = null
    ): NativeBoardPost = parseNativeBoardPost(
        request(
            "POST", "/native/session/" + encode(sessionId) + "/board", null,
            NativeRequests.boardPost(subject, body, refs)
        )
    )

    // ------------------------------------------------------------ tournaments

    fun startTournament(
        sessionId: String,
        goal: String,
        criteria: List<String>,
        n: Int,
        model: String? = null,
        maxTokens: Long? = null,
        maxCostMicro: BigInteger? = null,
        mutationMode: String? = null,
        files: List<String>? = null
    ): NativeTournamentStarted = parseNativeTournamentStarted(
        request(
            "POST", "/native/session/" + encode(sessionId) + "/tournament", null,
            NativeRequests.startTournament(
                goal, criteria, n, model, maxTokens, maxCostMicro, mutationMode, files
            )
        )
    )

    fun tournamentState(sessionId: String, tournamentId: String): NativeTournament =
        parseNativeTournament(
            request(
                "GET",
                "/native/session/" + encode(sessionId) + "/tournament/" + encode(tournamentId)
            )
        )

    /** The durable tournament listing of one session (newest last). */
    fun tournaments(sessionId: String): List<NativeTournamentSummary> =
        parseNativeTournamentSummaries(
            request("GET", "/native/session/" + encode(sessionId) + "/tournaments")
        )

    /** Run the deterministic comparison; engine refusals are typed (404/409). */
    fun decideTournament(sessionId: String, tournamentId: String): NativeTournamentDecision =
        parseNativeTournamentDecision(
            request(
                "POST",
                "/native/session/" + encode(sessionId) + "/tournaments/" +
                    encode(tournamentId) + "/decide",
                null,
                NativeRequests.decideTournament()
            )
        )

    /** Abort one tournament with an optional reason; returns the durable state. */
    fun abortTournament(
        sessionId: String,
        tournamentId: String,
        reason: String? = null
    ): NativeTournament = parseNativeTournament(
        request(
            "POST",
            "/native/session/" + encode(sessionId) + "/tournaments/" +
                encode(tournamentId) + "/abort",
            null,
            NativeRequests.abortTournament(reason)
        )
    )

    // ------------------------------------------------------- orchestrator graph

    fun orchestratorGraph(sessionId: String): NativeOrchestratorGraph =
        parseNativeOrchestratorGraph(
            request("GET", "/native/orchestrator/graph", query("session" to sessionId))
        )

    // ------------------------------------------------- permissions (reply path)

    fun permissions(sessionId: String): List<NativePermissionEntry> =
        parseNativePermissionList(
            request("GET", "/native/permissions", query("session" to sessionId))
        )

    fun replyPermission(permissionId: String, decision: String): NativePermissionAck =
        parseNativePermissionAck(
            request(
                "POST", "/native/permission/reply", null,
                NativeRequests.permissionReply(permissionId, decision)
            )
        )

    // ------------------------------------------------- provider registry (P0-64)

    /** The registered provider instances with their known models. */
    fun providers(): List<NativeProviderInfo> =
        parseNativeProviders(request("GET", "/native/providers"))

    // ---------------------------------------------------- terminals (P0-62)

    /**
     * The session-scoped terminal projection. Only terminals durably owned by
     * [sessionId] appear; unowned legacy rows are counted in `unowned` and
     * named in `note` instead of leaking into the view.
     */
    fun terminals(sessionId: String): NativeTerminalPage =
        parseNativeTerminalPage(
            request("GET", "/native/terminals", query("session" to sessionId))
        )

    /** One bounded page of the session's terminal lifetime events. */
    fun terminalEvents(
        sessionId: String,
        after: Long? = null,
        limit: Long? = null
    ): NativeTerminalEventPage = parseNativeTerminalEventPage(
        request(
            "GET",
            "/native/session/" + encode(sessionId) + "/terminal/events",
            query("after" to after?.toString(), "limit" to limit?.toString())
        )
    )

    /** Spawn one session-owned terminal; strict body, server owns the bounds. */
    fun spawnTerminal(
        sessionId: String,
        command: String,
        args: List<String>? = null,
        cwd: String? = null,
        rows: Long? = null,
        cols: Long? = null
    ): NativeTerminalSpawned = parseNativeTerminalSpawned(
        request(
            "POST", "/native/session/" + encode(sessionId) + "/terminal", null,
            NativeRequests.spawnTerminal(command, args, cwd, rows, cols)
        )
    )

    /** Snapshot available output of one PTY (does not drain the buffer). */
    fun terminalOutput(sessionId: String, terminalId: String): NativeTerminalOutput =
        parseNativeTerminalOutput(
            terminalId,
            request(
                "GET",
                "/native/session/" + encode(sessionId) + "/terminals/" +
                    encode(terminalId) + "/output"
            )
        )

    // --------------------------------------------------------------- agents

    fun agents(sessionId: String): List<NativeAgent> = parseNativeAgents(
        request("GET", "/native/agents", query("session" to sessionId))
    )

    fun pauseAgent(childId: String): NativeAgentControlAck = agentControl(childId, "pause")

    fun resumeAgent(childId: String): NativeAgentControlAck = agentControl(childId, "resume")

    fun cancelAgent(childId: String): NativeAgentControlAck = agentControl(childId, "cancel")

    fun retryAgent(childId: String): NativeAgentControlAck = agentControl(childId, "retry")

    fun steerAgent(childId: String, text: String): NativeAgentControlAck =
        parseNativeAgentControlAck(
            request(
                "POST", "/native/agents/" + encode(childId) + "/steer", null,
                NativeRequests.steer(text)
            )
        )

    fun setAgentModel(childId: String, model: String): NativeAgentControlAck =
        parseNativeAgentControlAck(
            request(
                "POST", "/native/agents/" + encode(childId) + "/model", null,
                NativeRequests.changeModel(model)
            )
        )

    fun setAgentBudget(
        childId: String,
        maxTokens: Long? = null,
        maxCostMicro: BigInteger? = null
    ): NativeAgentControlAck {
        if ((maxTokens == null) == (maxCostMicro == null)) {
            throw NativeProtocolException(
                "setAgentBudget",
                "exactly one of maxTokens or maxCostMicro must be set"
            )
        }
        return parseNativeAgentControlAck(
            request(
                "POST", "/native/agents/" + encode(childId) + "/budget", null,
                NativeRequests.changeBudget(maxTokens, maxCostMicro)
            )
        )
    }

    /**
     * Durable presentation/attention transition of one child of
     * [sessionId]: `foreground` shows the child in the main tree,
     * `background` dims/tucks it. The server owns the terminal-child
     * refusal (typed 409) and the idempotent same-state no-op.
     */
    fun setAgentPresentation(
        sessionId: String,
        childId: String,
        presentation: String
    ): NativePresentationAck = parseNativePresentationAck(
        request(
            "POST",
            "/native/session/" + encode(sessionId) + "/agents/" + encode(childId) +
                "/presentation",
            null,
            NativeRequests.changePresentation(presentation)
        )
    )

    private fun agentControl(childId: String, action: String): NativeAgentControlAck =
        parseNativeAgentControlAck(
            request("POST", "/native/agents/" + encode(childId) + "/" + action)
        )

    // ------------------------------------------------------ usage / verification

    fun usage(): NativeUsageTotals = parseNativeUsage(request("GET", "/native/usage"))

    fun sessionUsage(sessionId: String): NativeSessionUsage = parseNativeSessionUsage(
        request("GET", "/native/session/" + encode(sessionId) + "/usage")
    )

    // ------------------------------------------------- commercial metering

    /** The caller's control-plane identity (fixes the billing organization). */
    fun identity(): NativeIdentity = parseNativeIdentity(request("GET", "/native/identity"))

    /** The derived entitlement snapshot of the caller's organization. */
    fun entitlements(): NativeEntitlementSnapshot =
        parseNativeEntitlements(request("GET", "/native/entitlements"))

    /**
     * The organization's usage fold plus ONE cursor page of its usage events.
     * `since` is the exclusive cursor a previous page returned as
     * `nextCursor`; the daemon bounds the page size (1..=200).
     */
    fun billingUsage(
        organization: String,
        since: String? = null,
        limit: Long? = null
    ): NativeBillingUsage = parseNativeBillingUsage(
        request(
            "GET", "/native/usage",
            query(
                "org" to organization,
                "since" to since,
                "limit" to limit?.toString()
            )
        )
    )

    /**
     * Grant credits (admin role only; the server is the guard). The daemon
     * REQUIRES the `Idempotency-Key` header: the same key + same request
     * replays the recorded result instead of appending a second grant.
     */
    fun grantCredits(
        amountMicro: BigInteger,
        idempotencyKey: String,
        reason: String? = null,
        accountId: String? = null
    ): NativeCreditGrant = parseNativeCreditGrant(
        request(
            "POST", "/native/credits/grant", null,
            NativeRequests.grantCredits(amountMicro, reason, accountId),
            maxBodyBytes,
            listOf(Pair("idempotency-key", idempotencyKey))
        )
    )

    /**
     * Revoke the caller's control-plane session (`POST /native/sso/logout`).
     * The route needs the daemon password (the bearer this client always
     * sends) AND the session's own token (`x-faktor-control-token`), plus the
     * STRICT body `{organization, session_id}` naming the session the token
     * must own. The session id is a NON-secret coordinate provisioned with
     * the credential; the token is never derivable from it. Server refusals
     * are typed: foreign/missing session 404, non-owning token 401, disabled
     * control plane 409 — the caller reports the refusal and the local
     * credential is still removed (never a claimed revoke).
     */
    fun revokeControlSession(organization: String, sessionId: String) {
        if (organization.isBlank() || sessionId.isBlank()) {
            throw NativeProtocolException(
                "POST /native/sso/logout",
                "revoking a control-plane session requires the organization and the auth-session id"
            )
        }
        request(
            "POST", "/native/sso/logout", null,
            NativeRequests.ssoLogout(organization, sessionId)
        )
    }

    fun verification(sessionId: String): NativeVerificationView = parseNativeVerificationView(
        request("GET", "/native/session/" + encode(sessionId) + "/verification")
    )

    fun taskVerification(sessionId: String, taskId: String): NativeTaskVerification =
        parseNativeTaskVerification(
            request(
                "GET",
                "/native/session/" + encode(sessionId) + "/tasks/" + encode(taskId) + "/verification"
            )
        )

    /**
     * The strict proof summary (`GET /native/tasks/{id}/proof`), session
     * scoped by the REQUIRED `session` query. Read-only and fail-closed: a
     * corrupt store read is a typed API error the caller renders as an
     * explicit unavailable state, never as VERIFIED.
     */
    fun taskProof(sessionId: String, taskId: String): NativeTaskProof =
        parseNativeTaskProof(
            request(
                "GET", "/native/tasks/" + encode(taskId) + "/proof",
                query("session" to sessionId)
            )
        )

    /** The durable per-step status/report read (proof drill-down). */
    fun taskCompletionSteps(sessionId: String, taskId: String): NativeTaskCompletionSteps =
        parseNativeTaskCompletionSteps(
            request(
                "GET", "/native/tasks/" + encode(taskId) + "/completion-steps",
                query("session" to sessionId)
            )
        )

    // ------------------------------------------------------------- evidence

    fun evidence(sessionId: String, evidenceId: Long): NativeEvidence = parseNativeEvidence(
        request(
            "GET", "/native/evidence/" + evidenceId,
            query("session" to sessionId)
        )
    )

    fun retrieveEvidence(
        sessionId: String,
        evidenceId: Long,
        selectorJson: String
    ): NativeEvidenceRetrieval = parseNativeEvidenceRetrieval(
        request(
            "POST", "/native/evidence/" + evidenceId + "/retrieve",
            query("session" to sessionId), selectorJson,
            EVIDENCE_MAX_BODY_BYTES
        )
    )

    // ------------------------------------------------------------- transport

    private fun query(vararg pairs: Pair<String, String?>): List<Pair<String, String>> {
        val out = ArrayList<Pair<String, String>>()
        for (pair in pairs) {
            if (pair.second != null) out.add(Pair(pair.first, pair.second!!))
        }
        return out
    }

    private fun encode(value: String): String = URLEncoder.encode(value, "UTF-8")

    private fun request(
        method: String,
        path: String,
        queryParams: List<Pair<String, String>>? = null,
        body: String? = null,
        maxBytes: Long = maxBodyBytes,
        extraHeaders: List<Pair<String, String>>? = null
    ): String {
        val url = StringBuilder(baseUrl.trimEnd('/')).append(path)
        if (queryParams != null && queryParams.isNotEmpty()) {
            url.append('?')
            for ((i, pair) in queryParams.withIndex()) {
                if (i > 0) url.append('&')
                url.append(encode(pair.first)).append('=').append(encode(pair.second))
            }
        }
        val builder = HttpRequest.newBuilder(URI.create(url.toString()))
            .timeout(Duration.ofMillis(timeoutMs))
            .header("Authorization", "Bearer $bearerToken")
            .header("Accept", "application/json")
        if (controlToken != null && controlToken.isNotEmpty()) {
            builder.header("x-faktor-control-token", controlToken)
        }
        if (extraHeaders != null) {
            for (header in extraHeaders) {
                builder.header(header.first, header.second)
            }
        }
        if (body != null) {
            builder.header("Content-Type", "application/json")
            builder.method(method, HttpRequest.BodyPublishers.ofString(body))
        } else {
            builder.method(method, HttpRequest.BodyPublishers.noBody())
        }
        val response = try {
            http.send(builder.build(), HttpResponse.BodyHandlers.ofInputStream())
        } catch (e: IOException) {
            throw NativeApiException(
                0, "transport",
                "$method $path failed (daemon down?): ${e.message}", true
            )
        } catch (e: InterruptedException) {
            Thread.currentThread().interrupt()
            throw NativeApiException(0, "transport", "$method $path interrupted", true)
        }
        val status = response.statusCode()
        val text = response.body().use { readBounded(it, maxBytes, "$method $path") }
        if (status !in 200..299) {
            throw apiError(status, text, "$method $path")
        }
        return text
    }

    /** Reads at most [maxBytes]; an oversized body is closed and rejected. */
    private fun readBounded(stream: InputStream, maxBytes: Long, path: String): String {
        val out = ByteArrayOutputStream()
        val buffer = ByteArray(8192)
        var total = 0L
        while (true) {
            val read = stream.read(buffer)
            if (read < 0) break
            total += read
            if (total > maxBytes) {
                throw NativeProtocolException(path, "response body exceeded bound $maxBytes bytes")
            }
            out.write(buffer, 0, read)
        }
        return String(out.toByteArray(), Charsets.UTF_8)
    }

    /** Maps a non-2xx body onto the daemon's typed error envelope. */
    private fun apiError(status: Int, body: String, path: String): NativeApiException {
        val parsed = try {
            JsonCodec.parse(body)
        } catch (e: NativeProtocolException) {
            return NativeApiException(status, "http_error", body.take(REQUEST_ERROR_SNIPPET), false)
        }
        val error = (parsed as? JsonValue.Obj)?.fields?.get("error") as? JsonValue.Obj
        val code = ((error?.fields?.get("code")) as? JsonValue.Str)?.value
        val message = ((error?.fields?.get("message")) as? JsonValue.Str)?.value
        val retryable = ((error?.fields?.get("retryable")) as? JsonValue.Bool)?.value
        if (code == null || message == null) {
            return NativeApiException(status, "http_error", body.take(REQUEST_ERROR_SNIPPET), false)
        }
        return NativeApiException(status, code, message, retryable == true)
    }
}
